### ISSUE TITLE
PCB Re-Review

### ISSUE THREAD

**Issue by mgood13** [mgood13/mgood13_Design_Skills_Project#10]
I've changed a few things about my PCB and I think that it's ready or hopefully close to ready to print, but wanted another set of eyes to look at it.

**Comment by mlp6** [comment]
A few comments:
* The battery is directly connected to the board... header pins instead?
* Nitpick... in the schematic, keep the connections at right angles to each other when possible. Just makes it easier to quickly scan since that is what most folks will be expecting.
* Ratwire to `T2` not made into trace.
* What is going on with the base connect for `T1`?

**Comment by mlp6** [comment]
Actually,  I think that more than the mentioned above connections might not be made on the PCB... take a closer look.

**Comment by mgood13** [comment]
I'm very sorry. I hadn't pushed up the correct schematics. I have pushed the correct ones up now: "Analog_Light_Project_Improved_Schematic"

**Comment by mlp6** [comment]
Some of the issues still persist in this revised version.  For example:
* A few traces are < 20 mil; need at least 20 mil for the photoetch.
* `LED1` `GND` pin doesn't appear to be connected on the PCB.
* If you only have a few traces on the bottom, we can probably get more creative and make this a single-sided board.  You may be able to use a thru-hole component as a bridge to jump over some traces, etc.
* In the schematic, keep the connection between `T1` and `R15` more visible by not crossing through `T1`.

**Comment by mgood13** [comment]
I think all the traces are 20mil now and I switched everything to a single side by adding in some thru hole components and tracing under those, is this what you meant?
Also, I have the LED grounded on the schematic, and it is labelled as ground on PCB, do I still need to route it back to the ground lead on the battery in order for it to be really connected to ground?

**Comment by mlp6** [comment]
Hmmm... maybe I opened the wrong PCB file... let me check again.

**Comment by mgood13** [comment]
Actually you're right. I didn't make the trace from the negative lead of the battery 20mil. I'll fix that now.
